package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'FailedBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("FailedBuild")) {
    features {
        add {
            commitStatusPublisher {
                vcsRootExtId = "SlackNotifierDsl_HttpsGithubComIyankeJavaEclipse"
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = personalToken {
                        token = "credentialsJSON:c65567b2-fa6c-44a4-b802-8255c774d6d2"
                    }
                }
            }
        }
    }
}
